### ISSUE TITLE
Create Alert Box for "Reservation Confirmation"

### ISSUE THREAD

**Issue by Ahzem** [Ahzem/Seyoni#62]
Develop a new alert box for the **Reservation Confirmation** message. This alert box should prompt users to confirm if they want to confirm their reservation, providing options to either cancel or proceed with the confirmation.

![Image](https://github.com/user-attachments/assets/6b9d6200-0344-4e3a-919c-5f4b30e443e3)

## Requirements
1. **Directory Structure**:
   - Save the alert box file in `lib/src/widgets/alertbox/`.

2. **Alert Box Details**:
   - **Message**: "Are you sure you want to confirm this reservation? Please review all details carefully."
   - **Buttons**:
     - **Cancel**: Button to close the alert box and return to the current page.
     - **Confirm**: Button to confirm the reservation.

3. **Design**:
   - Follow the design and styling conventions used in the project.
   - Ensure the alert box is responsive and works well on different screen sizes.

4. **Functionality**:
   - Implement the logic for displaying the alert box when the user initiates a reservation confirmation action.
   - Ensure the "Cancel" button closes the alert box without confirming the reservation.
   - Ensure the "Confirm" button confirms the reservation.

## Reference Directory Structure
```
lib
│───main.dart    
└───src
    │───widgets
    |    │──alertbox
    |    |    │──alert_reservation_confirmation.dart
```

## Acceptance Criteria
- [ ] An alert box is created with the specified message.
- [ ] The alert box contains "Cancel" and "Confirm" buttons.
- [ ] The "Cancel" button closes the alert box and keeps the user on the current page.
- [ ] The "Confirm" button confirms the reservation.
- [ ] The alert box follows the project's design and styling conventions.
- [ ] The alert box is responsive and works well on different screen sizes.
- [ ] The code is properly commented and follows the project's coding standards.

## Additional Notes
- Ensure the alert box integrates smoothly with the existing application.
- Test the functionality thoroughly to avoid any issues with the reservation confirmation process.

**Comment by Atharva-Werulkar** [comment]
Hello,

I'm excited to take on this issue. I have experience working with Flutter, including creating custom widgets and ensuring responsiveness across different devices. Here's how I plan to approach the implementation:

I'll create the alert box as per the directory structure you mentioned, following the project's design and styling guidelines.
The alert box will display the message: "Are you sure you want to confirm this reservation? Please review all details carefully." and include both the "Cancel" and "Confirm" buttons.
I’ll handle the logic to ensure that the "Cancel" button will simply close the alert without confirming the reservation, while the "Confirm" button will confirm the reservation.
I'll ensure responsiveness and proper functionality across different screen sizes, making sure it integrates smoothly with the existing application.
Finally, the code will be well-commented, adhering to the project's coding standards.
I look forward to contributing and will test the functionality thoroughly before submitting.

Best regards,
Atharva Werulkar

**Comment by Ahzem** [comment]
Hello Atharva,

Thank you for offering your support and sharing your approach! I truly appreciate your willingness to contribute.

However, this project is currently limited to a team of five members, and we've already reached that capacity. I’m sorry for any confusion caused, but we’d definitely love to stay connected for future projects where we could collaborate.

Thanks again for your understanding, and I hope we get to work together soon!

Best regards,
[Ahzem](https://www.linkedin.com/ahzem)
